
// first function

if1()
{
	b = 1;
	if (a)
		b = 2;
}

if2()
{
	if (a)
		b = 1;
	else
		b = 2;
}

if2_5(a,b)
{
	if (a || b)
		b = 1;
	else
		b = 2;
}

if3(a,b)
{
	if (a || b);
	else
		c = 1;
}

if4(a,b)
{
	if (a || b)
		c = 1;
	else;
}

if5(a,b)
{
	if (a || b);
	else;
}

if6(a,b)
{
	if (a || b)
		return 1;
	else
		return 2;
}

if7(a,b)
{
	if (a || b)
		if (a && b)
			return 1;
		else
			return 2;
	else
		return 3;
}

if8(a,b)
{
	if (a || b)
		return 1;
	else if (a && b)
		return 2;
	else
		return 3;
}

/*
/*

or1()
{
	a = b || c || d || f;
	a = 1 || 2;
}
and1()
{
	a = b && c && d && f;
	a = 1 && 2;
}
andor(a,b,c)
{
	return a || b && c;
}

/*

var()
{
	a = 1;
	b = "hello";
	return b;
}

return1()
{
	return;
}
return2()
{
	return a;
}
return3(a)
{
	return a;
}
return4(a, b)
{
	return b;
}

*

fun1() { }
fun2(a) { }
fun3(a, b) { }
fun4(a, b, c) { }

/*
fun1()
{
	if (a && b)
		return c;
	a = b;
	return a;
}
*/

