
// first function

or1()
{
	a = b || c || d || f;
	a = 1 || 2;
}
and1()
{
	a = b && c && d && f;
	a = 1 && 2;
}
andor(a,b,c)
{
	return a || b && c;
}

/*

var()
{
	a = 1;
	b = "hello";
	return b;
}

return1()
{
	return;
}
return2()
{
	return a;
}
return3(a)
{
	return a;
}
return4(a, b)
{
	return b;
}

*

fun1() { }
fun2(a) { }
fun3(a, b) { }
fun4(a, b, c) { }

/*
fun1()
{
	if (a && b)
		return c;
	a = b;
	return a;
}
*/

